insert into "fresh" values ( 1, 'fresh-1',  '新人　一郎');
insert into "fresh" values ( 2, 'fresh-2',  '新人　二郎');
insert into "fresh" values ( 3, 'fresh-3',  '新人　三郎');
insert into "fresh" values ( 4, 'fresh-4',  '新人　四郎');
insert into "fresh" values ( 5, 'fresh-5',  '新人　五郎');
insert into "fresh" values ( 6, 'fresh-6',  '新人　六郎');
insert into "fresh" values ( 7, 'fresh-7',  '新人　七郎');
insert into "fresh" values ( 8, 'fresh-8',  '新人　八郎');
insert into "fresh" values ( 9, 'fresh-9',  '新人　九郎');
insert into "fresh" values (10, 'fresh-10', '新人　十郎');
